
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import Footer from './footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="flex justify-between m-5">
            <div>
              <Link href="/" className="bg-gray-400 rounded-lg hover:bg-gray-500 cursor-pointer p-2 mr-2">
                Home
              </Link>
            </div>
            <div>
              <Link href="/indicators"
               className="bg-gray-400 rounded-lg hover:bg-gray-500 cursor-pointer p-2 mr-2">Indicators
              </Link>
              <Link href="/about"
                className="bg-gray-400 rounded-lg hover:bg-gray-500 cursor-pointer p-2 mr-2">About
              </Link>
              <Link href="/register"
                className="bg-gray-400 rounded-lg hover:bg-gray-500 cursor-pointer p-2 mr-2">Register
              </Link>           
            </div>
          </div>
          {children}
        </div>
      </body>
      <Footer />
    </html>
  )
  
}


